version = 0.1

[default]
[default.global.parameters]
stack_name = "backend"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "backend"
region = "eu-central-1"
profile = "pcd-homework-2"
image_repositories = []
parameter_overrides = [
    "Stage=\"Production\"",
    "DatabaseUsername=\"postgres\"",
    "DatabasePassword=\"pcdhomeworktwo\"",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
